### ISSUE TITLE
add line break on question mark , exclamation and periods

### ISSUE THREAD

**Issue by codewithnick** [PCON-Hacktoberfest-2022/Textutils#15]
example: 

input : "Hello, I am a student! currently studying at nit jamshedpur. how are you? "

output: 
"Hello, I am a student! 
currently studying at nit jamshedpur. 
how are you? "

**Comment by codewithnick** [comment]
hi can you please assign me this issue

**Comment by Prakhar9450** [comment]
Please assign me this issue i will definitely help with it

**Comment by Dipti821** [comment]
Its done @Prakhar9450
