### ISSUE TITLE
Undo

### ISSUE THREAD

**Issue by ggautamgoyalg** [PCON-Hacktoberfest-2022/Textutils#23]
The feature to undo the changes made on text

**Comment by Rishi-uh** [comment]
would like to work on this, please assign this to me @Dipti821

**Comment by ggautamgoyalg** [comment]
**ma'am can you please assign me this issue**

**Comment by Dipti821** [comment]
@Rishi-uh since this issue is opened by @ggautamgoyalg I am assigning him this issue.
