### ISSUE TITLE
Dark mode and light mode toggle icon issue

### ISSUE THREAD

**Issue by Waishnav** [PCON-Hacktoberfest-2022/Textutils#4]
**Steps to reproduce**
Click on the toggle icon at the right side corner and click on it multiple times

**Behaviour reproduced**
sometime it toggled to dark mode sometime it didn't.

**Ideal Behaviour**
Toggle icon should be toggled to dark mode after clicking.

**Comment by Waishnav** [comment]
Also can I work on this issue??

**Comment by Dipti821** [comment]
Yup @Waishnav you can work in this issue.
