### ISSUE TITLE
Resolve existing syntax errors

### ISSUE THREAD

**Issue by chikaldirick** [PCON-Hacktoberfest-2022/Textutils#41]
Currently there are several things in the project that do not allow to run it after local setup. Here are most crucial ones:
- `capitalizeFirstWord` function does not have a closing curly brace (https://github.com/PCON-Hacktoberfest-2022/Textutils/blob/main/src/components/TextForm.js#L64) so the project can't be started.
- therefore some functions like `handleCopy` are duplicated (have two definitions) - this becomes an error when you resolve the 1st issue

As a result bring the codebase to the working state so the project runs on a first try without errors.

**Comment by chikaldirick** [comment]
@Dipti821, I've resolved existing issues within PR https://github.com/PCON-Hacktoberfest-2022/Textutils/pull/42
The changes there are split by commits: each improvement is a separate commit. Feel free to check it out when you have spare time.
Doing this not to earn some hacktoberfest reward but to make project's codebase more consistent and stable.

**Comment by Dipti821** [comment]
Thank you for your hardwork @chikaldirick  I checked it out it looks good to me.
