### ISSUE TITLE
Bug in Capitalize first word

### ISSUE THREAD

**Issue by Dipti821** [PCON-Hacktoberfest-2022/Textutils#45]
It is not capitalising the first word occuring in new line or just after some punctuation. Correct it.

**Comment by najeebkp** [comment]
Hi @Dipti821 Please assign me this

**Comment by Rishi-uh** [comment]
please assign me this issue @Dipti821

**Comment by Dipti821** [comment]
> please assign me this issue @Dipti821

@Rishi-uh someone is already working in this issue.
