### ISSUE TITLE
Add feature: Toggle the case.

### ISSUE THREAD

**Issue by prabhat7k** [PCON-Hacktoberfest-2022/Textutils#48]
> If the letter is in lowercase convert to uppercase

> If the letter is in uppercase convert to lowercase

**Comment by prabhat7k** [comment]
@Dipti821 please assign this to me under hacktoberfest

**Comment by Dipti821** [comment]
@prabhat7k textutils already have this feature so I don't find this issue valid.

**Comment by prabhat7k** [comment]
I meant Toggle the case.
Example: this IS a ExamplE
=> THIS is A eXAMPLe

**Comment by prabhat7k** [comment]
![image](https://user-images.githubusercontent.com/83745263/194736296-18e1ab4d-d79f-4075-a8dd-43dcb08b3a2b.png)


![image](https://user-images.githubusercontent.com/83745263/194736316-bf328dcb-910e-4920-92ee-b45d9b2656c7.png)

**Comment by Dipti821** [comment]
Srry I didn't understand the issue previously. When you are raising a issue you should explain it properly with an example.

**Comment by prabhat7k** [comment]
> Srry I didn't understand the issue previously. When you are raising a issue you should explain it properly with an example.

I'll take care of it next time.

**Comment by prabhat7k** [comment]
@Dipti821 I've solved this issue in PR #51
