### ISSUE TITLE
Add Footer

### ISSUE THREAD

**Issue by Dipti821** [PCON-Hacktoberfest-2022/Textutils#63]

**Comment by yhoungdev** [comment]
.taken

**Comment by syprogrammer** [comment]
can you assign me

**Comment by Dipti821** [comment]
Since @yhoungdev commented first I am assigning him. @syprogrammer you can work on other issues.

**Comment by Dipti821** [comment]
> .taken

Are you working on it?

**Comment by yhoungdev** [comment]
Yes will push the PR today
